In [57]:
import numpy as np
print (np.__version__)

1.24.3


In [3]:
list=[23,34,45]
print(list[-1])
#Print (List,type(list),id(list) )

45


In [6]:
b=np.array([[1,2,3],[1,2,3]])
print(b,type(b))
print(b.ndim)

[[1 2 3]
 [1 2 3]] <class 'numpy.ndarray'>
2


In [8]:
print(b.ndim)

2


In [10]:
a=np.array([[[1,2,3],[1,2,3],[1,2,3],[1,2,3]]])
#print (a,type(a))
print(a)
print(a.ndim)

[[[1 2 3]
  [1 2 3]
  [1 2 3]
  [1 2 3]]]
3


In [11]:
print(a.ndim)

3


In [15]:
#Methods Zeros(),One ()
c=np.zeros((4,5))
print(c.ndim)
c

2


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

ZEROS(),ONES()are the NumPy Liberary Functions to create two different arrays.zeros() function is used to create an array based on particular shape & type . All array elements are itialized to 0, which is create by zeros() functions. one() function works like the zero () function.

In [16]:
a=np.zeros((3,4))
print(a.ndim)

2


In [18]:
#c=np.Ones(10)*5
#Print(c)
a=np.ones((3,3))
print (a)
a.ndim

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


2

In [19]:
a=np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [20]:
a=np.eye(6,k=-3)
print(a)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]


In [21]:
a=np.full((3,4),89)
print(a)

[[89 89 89 89]
 [89 89 89 89]
 [89 89 89 89]]


In [23]:
a=np.random.rand(5,5)
print(a)

[[0.94235825 0.54384112 0.50408088 0.32998986 0.76724663]
 [0.79058353 0.53266689 0.27738081 0.59706041 0.89700268]
 [0.77090711 0.09833514 0.67511065 0.26862813 0.90904883]
 [0.56745917 0.41867369 0.5219654  0.93442057 0.96379901]
 [0.01391745 0.42453269 0.35938914 0.77692559 0.05106043]]


In [27]:
a=np.random.randn(5,5) #n Means Negative Values 
print(a)
print(a.ndim)
print(a.dtype)
print(a.shape)
print(a.size)

[[-1.14196555 -0.3778205   0.08068871 -0.86208047  0.30967229]
 [-0.15280002  0.46434634 -1.16523002 -0.93520521  0.28066342]
 [ 0.29787039 -0.82199144  0.96892113  0.28453878  0.84696975]
 [ 0.22129872 -0.02072122  0.33443857  1.37010898  2.37493569]
 [ 0.74534686  0.30223004 -1.51486563 -0.51498243  0.81149759]]
2
float64
(5, 5)
25


In [29]:
s=np.linspace (0,1,20)
print(s)
print(s.ndim)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]
1


In [30]:
#a=np.array 

In [31]:
#a=random.uniform (a,b) #Provide interger Values
#Print

In [34]:
#Properties of Array 
a=np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])
print(a)
print(a.ndim)
print(a.dtype)
print(a.shape)
print(a.size)

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]
3
int32
(3, 2, 3)
18


In [ ]:
#Copy () And View() the main differece between a  copy & a view of an array is that the copy is a new arrary,
#and the view is just a view of the original array. 

In [37]:
a=np.array([1,2,3])
x=a.copy()
x[0]=10
print("Orginal Values",a)
print("Copy Values",x)
print("*"*30)

#View 
a=np.array([1,2,3])
y=a.view()
y[0]=10
print("orignal values",a)
print("view values",y)

Orginal Values [1 2 3]
Copy Values [10  2  3]
******************************
orignal values [10  2  3]
view values [10  2  3]


In [53]:
#Indexing & Slicing 
a1=np.array([[1,2,3],[4,5,6],[7,8,9]])
#print("Orignal:",a)
#print(a)
#print()
a=[1,2,3,4,5]
#print(a1[2:4])
print(a1)
print(a1[0])
print(a1.ndim)
print(a1[0,2])
print(a1[2,1])
print(a1[0:,0:33])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
2
3
8
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [73]:
a=np.array([[[1,2,3],[1,2,3]],[[4,5,6],[4,5,6]]])
print(a.ndim)
print(a)
#print(a[:,0,2])
#print(a[1])
#print(a[2])-Will give error as 2nd  array is not present.
#print(a[1:,1:])
#print(a[:,1,2])
#print(a[1,:])

3
[[[1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]]]


In [105]:
#Array Operation 

x=np.array([1,2,3])
print("original",x)
print("Single dimensinal")
y=np.append(x,[4,5,6])
print("second array",y)
print("*"*40)



original [1 2 3]
Single dimensinal
second array [1 2 3 4 5 6]
****************************************


In [106]:
a=np.array([[1,2,3],[1,2,3],[1,2,3]])
print("Second dimensinal array",a)
print("*"*40)

b=np.append(a,[[4,5,6,7],[1,2,3,4],[4,5,6,7]])
print("After horixonal append with 1 dimension")
print(b)
print("*"*40)


Second dimensinal array [[1 2 3]
 [1 2 3]
 [1 2 3]]
****************************************
After horixonal append with 1 dimension
[1 2 3 1 2 3 1 2 3 4 5 6 7 1 2 3 4 4 5 6 7]
****************************************


In [111]:
a=np.array([[1,2,3],[1,2,3],[1,2,3]])
c=np.append(a,[[4,5,6,6],[1,2,3,4],[4,5,6,7]],axis=1)
print("axis 1 positional:")
print(c)

print('#'*40)

d=np.append(a,[[4,5,6],[1,2,3],[4,5,6]],axis=1)
print("axis 0 positions")
print(d)

axis 1 positional:
[[1 2 3 4 5 6 6]
 [1 2 3 1 2 3 4]
 [1 2 3 4 5 6 7]]
########################################
axis 0 positions
[[1 2 3 4 5 6]
 [1 2 3 1 2 3]
 [1 2 3 4 5 6]]


In [97]:
#Insert

a=np.array([1,2,3])
print(a)
b=np.insert(a,3,4)
print("After Insert",b)


[1 2 3]
After Insert [1 2 3 4]


In [102]:
#Delete 

a=np.array([[1,2,3],[11,12,13],[21,22,23]])
print(a)
c=np.delete(a,4)
print(c)
c=np.delete(a,[1,4,7])
print(c)

[[ 1  2  3]
 [11 12 13]
 [21 22 23]]
[ 1  3 11 13 21 23]


In [129]:
List1=([2,3,4])
List2=([3,5,6])
a=List1+List2
print("list cancat",a)

list cancat [2, 3, 4, 3, 5, 6]


In [128]:
a=np.array([[1,1],[2,2]])
b=np.array([[3,3],[4,4]])
print (a)
print (b)
print ("*"*50)

print(np.concatenate((a,b),axis=0))
print("*"*50)

print (np.concatenate ((b,a)))
print("*"*50)

print(b.T)

a=[2,3,4]
b=[3,4,5]
c=a+b
print(c)

[[1 1]
 [2 2]]
[[3 3]
 [4 4]]
**************************************************
[[1 1]
 [2 2]
 [3 3]
 [4 4]]
**************************************************
[[3 3]
 [4 4]
 [1 1]
 [2 2]]
**************************************************
[[3 4]
 [3 4]]
[2, 3, 4, 3, 4, 5]


In [117]:
list1=[2,3,4]
list2=[3,5,6]
a=list1+list2
print(a)

[2, 3, 4, 3, 5, 6]


In [118]:
a=np.array([1,2,4])
aa=np.array([1,2,3])
print(a+aa)

[2 4 7]


In [119]:
#BROADCASTING 

#print(list1+2) #TypeError: can only concatenate list(not "Int") to list.

print(a+2) #With Array


[3 4 6]
